### ISSUE TITLE
Missing shortcut opportunity

### ISSUE THREAD

**Issue by floriensk** [carlosjeurissen/cj-we-reopen-in-private#4]
Dear @carlosjeurissen,

I think this is the type of add-on that would really make use of the functionality of being able to assing a shortcut to it. Since the operation the add-on does is not performed so often, I, for example, keep its icon in the drop-down list for additional add-ons so that it doesn't take up much space in the main bar. However, this way it is extremely slow to use the extension.

If a shortcut could be assigned to the operation of opening the tab in a private window, it could be used more seamlessly.
Thanks!

**Comment by carlosjeurissen** [comment]
Good catch @floriensk . In Google Chrome you can assign a keyboard shortcut for activation of the extension by default. However this is not the case for Firefox. I've updated the extension to v1.2 which adds this ability.

**Comment by floriensk** [comment]
Nice work @carlosjeurissen, thanks for the quick implementation and the really useful extension!

**Comment by carlosjeurissen** [comment]
@floriensk You are very welcome!

**Comment by floriensk** [comment]
@carlosjeurissen for me the extension doesn't open a new private window now, it just closes the tab (somtimes it doesn't even close it).

**Comment by carlosjeurissen** [comment]
Thanks for letting me know! I'll investigate. Will keep you updated.

-------- Original Message --------

**Comment by floriensk** [comment]
Sorry, I've messed up this Issue quite a bit already, but I realized what has happened:
I didn't notice there was a private window open on the next virtual desktop. But I guess the extension cannot switch the current virtual desktop to the one that has that window open, could it?

**Comment by carlosjeurissen** [comment]
Are you sure the "allow in private" toggle was set to "allow"? Just updated to v1.3.1 which shows this warning when it is an issue.

Version 1.3.1 now also focuses private window after reopening the tab.

Did all issues get resolved?

**Comment by floriensk** [comment]
Carlos, now it works absolutely fantastic! Even across virtual desktops, which is wonderful.
As simple the purpose of the extension is, as much you are making out of it! Thanks for the ever-quick responses!
